# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ctt-ci

    steps:
    - uses: actions/checkout@v3
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v3
#      with:
#        dotnet-version: 6.0.x
    - name: Restore dependencies .NET
      run: |
        dotnet restore "${{github.workspace}}\WorkBC Career Transition Tool API\WorkBC Career Transition Tool API.csproj"
        dotnet restore "${{github.workspace}}\WorkBC Career Transition Tool API Tests\WorkBC Career Transition Tool API Tests.csproj"
    - name: Build .NET
      run: |
        dotnet build --no-restore "${{github.workspace}}\WorkBC Career Transition Tool API Tests\WorkBC Career Transition Tool API Tests.csproj"
        dotnet build --no-restore "${{github.workspace}}\WorkBC Career Transition Tool API\WorkBC Career Transition Tool API.csproj"
#    - name: Test .NET
#      run: dotnet test --no-build --verbosity normal
    - name: Publish .NET
      run: dotnet publish "WorkBC Career Transition Tool API\WorkBC Career Transition Tool API.csproj" -o ./Publish -c Release --no-self-contained
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.16.1'
    - run: npm install
      working-directory: "WorkBC Career Transition Tool WEB/careerTransitionTool"
    - run: powershell/CreateEnv.ps1 ${{github.workspace}}
    - run: npm run build
      working-directory: "WorkBC Career Transition Tool WEB/careerTransitionTool"
#    - run: npm test
    - name: Upload artifacts - frontend
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: WorkBC Career Transition Tool WEB/careerTransitionTool/public/
    - name: Upload artifacts - backend
      uses: actions/upload-artifact@v3
      with:
        name: api
        path: Publish/        
