# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: deploy DEV

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  cd:
    name: cd
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: check out repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Download artifacts
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        branch: master
        name: website
        path: downloads
    - name: Display structure of downloaded files
      run: ls -R
