# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: deploy DEV

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  cd:
    name: cd
    runs-on: ctt-cd-dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: check out repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Download artifacts - frontend
#      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        branch: master
        name: web
        path: downloads/web
    - name: Download artifacts - backend
#      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        branch: master
        name: api
        path: downloads/api
    - name: Display structure of downloaded files
      run: ls -R
    - name: Script
      run: ./Deploy.ps1
      shell: pwsh
